apiVersion: v1
kind: Service

metadata:
  name: blue-green-service2
  labels:
    app: blue-green-demo2
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: http-port
      protocol: TCP
  selector:
    app: green
